### ISSUE TITLE
Update project description on Github, still says "Tickle"

### ISSUE THREAD

**Issue by kylecordes** [angular/sickle#105]
It looks like maybe this project used to be named Tickle - and it still says that on the Github project description shown prominently. "Tickle - TypeScript to Closure Annotator"

This issue is a reminder to eventually adjust that.

**Comment by martine** [comment]
@mprobst I think I lack administrative access to this repo, or I'd fix this myself.

**Comment by mprobst** [comment]
@martone fixed.

Evan Martin <notifications@github.com> schrieb am Fr., 18. März 2016 um
09:21 Uhr:

**Comment by martine** [comment]
Thanks for reporting this!
