### ISSUE TITLE
cannot annotate rxjs

### ISSUE THREAD

**Issue by alexeagle** [angular/sickle#109]
fails here:
https://github.com/ReactiveX/rxjs/blob/1104af1c9996662eba51d9f0209d4924b5ae6ed4/src/operator/combineLatest.ts#L26

with `compiler should have enforced array type for rest param`

**Comment by rkirov** [comment]
It took awhile for me to parse it, but it is an Array type. Interesting ...

**Comment by martine** [comment]
I got it.
