### ISSUE TITLE
bad syntax in type

### ISSUE THREAD

**Issue by alexeagle** [angular/sickle#117]
in the emit for angular2 `angular2/github/modules/angular2/src/core/di/provider.js`

```
let Provider = class {
    /**
     * @param token
     * @param {!?} param0
     */
    constructor(token, { useClass, useValue, useExisting, useFactory, deps, multi }) {
        this.token = token;
        this.useClass = useClass;
        this.useValue = useValue;
        this.useExisting = useExisting;
        this.useFactory = useFactory;
        this.dependencies = deps;
        this._multi = multi;
    }
}
```

the `!?` seems suspicious, and causes a closure compiler crash (http://b/27642699)

**Comment by martine** [comment]
It's a non-nullable unknown.  :D

I will change the emit to use a plain `?`.

**Comment by alexeagle** [comment]
I suppose there could be such a thing as a type that allows all values
except null? But it doesn't work well at present (fyi it currently blocks
js_binary of angular2
