### ISSUE TITLE
Collapse duplicated module requires

### ISSUE THREAD

**Issue by martine** [angular/sickle#118]
```js
import {A} from './foo';
import {B} from './foo';

A, B;
```
becomes
```js
var foo_1 = require('./foo');
var foo_2 = require('./foo');
foo_1.A, foo_2.B;
```

We need to collapse those multiple requires into 
```js
var foo_1 = require('./foo');
var foo_2 = foo_1;
```

(This is not just a thing that can be handled by the user by just avoiding double imports, because if you'll get the duplicate identifiers also if you import and export from the same module.)

**Comment by martine** [comment]
Part of issue #111.

**Comment by alexeagle** [comment]
note, everything I've tried here is very slow (like >5m to compile angular2)
so I'm not sending a PR from https://github.com/angular/sickle/tree/ajd

It seems like even with hash-based map lookup, it is too expensive to check every import statement against the previously seen ones. If the imports were known to be ordered by clang-format, then we would be able to do this in O(1). Do you have any ideas?

**Comment by martine** [comment]
It can't be that expensive, are you sure it's your code?  Perhaps your code is just enabling compilation to make more progress and something after it is making this slow?  A given file has at most ~50 imports, and even using an array it's only 50^2 = 2500 steps which should be a fraction of a second.

**Comment by alexeagle** [comment]
I'm pretty sure this change causes it. In a clean client I can build
angular2 and deps in under 2m, but it's over 5m in the client with the
sickle change.
