### ISSUE TITLE
Disable tslint forin check

### ISSUE THREAD

**Issue by martine** [angular/sickle#125]
```
[16:19:04] [gulp-tslint] error (forin) main.ts[190, 3]: for (... in ...) statements must be filtered with an if statement
```

This is saying that if you use a for-in statement, you must write it like
```
for (let x in y) {
  if (y.hasOwnProperty(x)) {  // <- this is required
    ...
  }
}
```

This is to protect against people who add stuff to Object.prototype, but in sickle we don't do that so we shouldn't need to worry about this.

...I think?  Martin, what do you think?

**Comment by mprobst** [comment]
What about writing `for (let x of Object.keys(y)) { ... }`? A bit more wordy, but safer and a bit more readable? I assume people adding enumerable properties onto Object.prototype is a thing of the past, but the readability of `Object.keys()` is kind of nice. I don't feel strongly about it though.

The Real Fix (tm) of course is to make our stuff run with ES6 Maps.

**Comment by martine** [comment]
That is a good workaround, I agree.

ES6 maps are unfortunately hard to use with TS.  :~(

**Comment by probfacile** [comment]
typescript doesn't mention such:
https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html
