### ISSUE TITLE
tslint no-string-literal check is wrong

### ISSUE THREAD

**Issue by martine** [angular/sickle#126]
```
[16:19:04] [gulp-tslint] error (no-string-literal) main.ts[43, 18]: object access via string literals is disallowed
```

However, the object in question is from minimist and defined as

```js
		export interface ParsedArgs {
			[arg: string]: any;
			_: string[];
		}
```

so I should be able to index into it with a string.

What's the fix -- fix tslint or fix our settings?

**Comment by mprobst** [comment]
I think this rule does not do what I hoped it'd do. It just checks if whatever is in the brackets could in theory be a valid identifier on the object, but not whether the object allows it :-(

@alexeagle do you know if tslint does or will support type based checks?

**Comment by alexeagle** [comment]
https://github.com/palantir/tslint/issues/680

They can't run the typechecker because they only do file-by-file analysis
without typechecking. This is motivating the design of something they
haven't shown me called tsvet, as well as my thing
