### ISSUE TITLE
Stub decls must appear after "super" call

### ISSUE THREAD

**Issue by martine** [angular/sickle#27]
```javascript
class Foo {
  constructor(public x: string) {
    super(3);
  }
}
```

becomes

```javascript
class Foo {
  constructor(public x: string) {

// Sickle: begin stub declarations.

 /** @type { string} */
this.x;
// Sickle: end stub declarations.

    super(3);
  }
}
```

It's illegal in TS to have code before the super call apparently.

**Comment by martine** [comment]
To be clear (I double-checked this), the super() must be first when the class contains initialized properties or parameter properties.  (That's the TS error message.)

I think this means we can rely on looking for the super() in the body of the function as the first statement.  (If it's not there we can just bail on stub decls because TS will reject the code anyway).

**Comment by martine** [comment]
It turns out to be rather subtle when this rule applies, but I have a different approach that makes everything simpler.  I am sad I have to throw away my painstakingly gathered code, so I log here it here for posterity.

```javascript
// isSuperCall returns true if the given node is a super(...) call.
function isSuperCall(node: ts.Node): boolean {
  if (node.kind != ts.SyntaxKind.ExpressionStatement) return false;
  let expr = (<ts.ExpressionStatement>node).expression;
  if (expr.kind != ts.SyntaxKind.CallExpression) return false;
  let callTarget = (<ts.CallExpression>expr).expression;
  return callTarget.kind == ts.SyntaxKind.SuperKeyword;
}
```

**Comment by rkirov** [comment]
+1 for relying on type declaration hoisting. 

Thanks for the posterity :) You never know when that would be useful.
