### ISSUE TITLE
Synthetic ctor needs to call base class ctor with proper arguments

### ISSUE THREAD

**Issue by martine** [angular/sickle#38]
```javascript
class SuperTestBase {
  constructor(public x: number) {}
}
class SuperTestDerivedNoCTor extends SuperTestBase {
  foobar: number = 3;
}
```

Sickle generates a constructor for the derived class here, to have a place to declare the type of `foobar`.

But the existence of a constructor means that we need to call the constructor of the base class, which means we need to be able to reconstruct the constructor parameters as well as the parameters to super.

I think this means we might need to store a map of classes to the expected parameters of the ctor, which might even mean needing to do cross-file analysis... :~(

I tried a hack like this but it didn't go.  I might be able to turn off some type checking and force it though.
```javascript
constructor(...args: any[]) {
  super(...args);
```

**Comment by mprobst** [comment]
`super.call(this, arguments);` ?

Evan Martin <notifications@github.com> schrieb am Di., 2. Feb. 2016 um
15:21 Uhr:

**Comment by martine** [comment]
A good thought, but no:

http://www.typescriptlang.org/Playground#src=class%20SuperTestBase%20%7B%0A%20%20constructor(public%20x%3A%20number)%20%7B%7D%0A%7D%0Aclass%20SuperTestDerivedNoCTor%20extends%20SuperTestBase%20%7B%0A%20%20foobar%3A%20number%20%3D%203%3B%0A%20%20constructor()%20%7B%0A%09%20super(this%2C%20arguments)%3B%20%0A%20%20%7D%0A%7D

**Comment by martine** [comment]
The Closure compiler might accept this:
```javascript
class Foo {
  /** @type {number} */
  y;
}
```

At least, it recognizes it as ES6 typed mode and when it encounters it (if you set the typed flag) it hits this code:
  private void recordTypeSyntax(SourceRange location) {
    if (hasJsDocTypeAnnotations) {
      errorReporter.error("Can only have JSDoc or inline type annotations, not both",
          sourceName, lineno(location.start), charno(location.start));
    }
  }

**Comment by mprobst** [comment]
`ES6_TYPED` is the mode we hacked into JSCompiler when we thought we could just teach it TS (or something close enough). I don't think it's supported or particularly well working, so I'd recommend not relying on it.

**Comment by martine** [comment]
Apparently this works!?

```js
class Foo {
  bar() {
    /** @type {number} */
    this.x = 3;
  }
}

let x = new Foo();
console.log(x.x);
```

Without the @type annotation it complains about x not being a property.  So maybe we can just generate a fake helper that adds closure types.

**Comment by martine** [comment]
Fixed!
