### ISSUE TITLE
Transpiling causes confusing line numbers in output

### ISSUE THREAD

**Issue by martine** [angular/sickle#46]
When using sickle, the compiler error messages you get are relative to the sickle output, which means that file offsets are wrong.

One idea is to ensure that sickle output has output lines in the same place as input lines, which means generating code that (for example) doesn't use newlines.  That at least makes line numbers line up.

But in cases where we generate a synthetic constructor there's not a particular line in the source we are modifying, so we may be forced to add a new to the source.  But maybe even then we could do a rule like "stuff all synthetic code in one line in the very bottom of the class, right before the closing curly brace".

**Comment by mprobst** [comment]
If TypeScript read source maps, we could generate an appropriate source map
using e.g. https://github.com/mozilla/source-map.

Evan Martin <notifications@github.com> schrieb am Mi., 3. Feb. 2016 um
15:18 Uhr:

**Comment by martine** [comment]
But do our downstream compilers (both TSC and Cosure) know to emit error messages relative to their source map position?

Also relevant, issue #18.

**Comment by mprobst** [comment]
I've asked in our #typescript channel, let's see. That would be a useful
feature for sure. In the worst case, we could patch them up ourselves, it's
not that hard.

Evan Martin <notifications@github.com> schrieb am Do., 4. Feb. 2016 um
08:39 Uhr:

**Comment by martine** [comment]
I think I'm going to fix this in the google-internal wrapper of the TypeScript compiler.  That means there's nothing for Sickle to do.  It's a little too bad that means that others will still have this problem... maybe in the future the TS API will let us inject sickle in a way that works better.

**Comment by mprobst** [comment]
Maybe we could make sickle a 100% identical wrapper of TypeScript?

Evan Martin <notifications@github.com> schrieb am Sa., 13. Feb. 2016, 03:46:

**Comment by martine** [comment]
That's not a bad idea!  I will leave this open and think about it.

**Comment by martine** [comment]
Closing this in favor of #104, which includes doing this right.
