### ISSUE TITLE
Translate TypeScript Object Types (aka type literals) to Closure structs

### ISSUE THREAD

**Issue by mprobst** [angular/sickle#6]
E.g.

```ts
var litType: {someField: number};
```

Should become:

```js
var /** {{someField: number}} */ litType;
```

**Comment by martine** [comment]
Oops, I accidentally started on this without grabbing the bug.

**Comment by martine** [comment]
Actually, I'm not sure what this bug is asking for.  The description mentioned @typedef but the example doesn't use it.

**Comment by mprobst** [comment]
I think I started writing an issue about the first thing, and then was already on the next thing when filling out the body. Talk about attention span issues...

In any case, translating object types as shown in the example above seems useful.

**Comment by martine** [comment]
This was fixed with my recent type translation work.
