### ISSUE TITLE
Preserve TypeScript type coercions in Closure code

### ISSUE THREAD

**Issue by martine** [angular/sickle#65]
Input:
```javascript
function foo(str: string) {}
foo(<string>JSON.parse('"foo"'));
```

Outputs:
```javascript
// @param {string} str
function foo(str) { }
foo(JSON.parse('"foo"'));
```

We drop the `<string>` so Closure doesn't know about the type cast, producing a warning.

**Comment by martine** [comment]
Due to https://github.com/Microsoft/TypeScript/issues/6982 , I can't find any way to make TS preserve an inline Closure type coercion.

Start from this:
http://www.typescriptlang.org/Playground#src=let%20x%20%3D%20%2F**%20foo%20*%2F(3)%3B
and see if you can find some combination of parens etc. to make it work... hmm.

**Comment by mprobst** [comment]
@martine maybe we could contribute an upstream patch?

Evan Martin <notifications@github.com> schrieb am Do., 18. Feb. 2016 um
00:27 Uhr:
