### ISSUE TITLE
Enum written with incorrect reverse map

### ISSUE THREAD

**Issue by alexeagle** [angular/sickle#97]
from angular2/github/modules/angular2/src/compiler/url_resolver.ts
```
enum _ComponentIndex {
  Scheme = 1,
  UserInfo,
  Domain,
  Port,
  Path,
  QueryData,
  Fragment
}
```

TS/sickle produces this ES6 code:
```
var _ComponentIndex;
(function (_ComponentIndex) {
    _ComponentIndex[_ComponentIndex["Scheme"] = 1] = "Scheme";
    _ComponentIndex[_ComponentIndex["UserInfo"] = 2] = "UserInfo";
    _ComponentIndex[_ComponentIndex["Domain"] = 3] = "Domain";
    _ComponentIndex[_ComponentIndex["Port"] = 4] = "Port";
    _ComponentIndex[_ComponentIndex["Path"] = 5] = "Path";
    _ComponentIndex[_ComponentIndex["QueryData"] = 6] = "QueryData";
    _ComponentIndex[_ComponentIndex["Fragment"] = 7] = "Fragment";
})(_ComponentIndex || (_ComponentIndex = {}));
_ComponentIndex.Scheme = 1;
_ComponentIndex.UserInfo = 0;
_ComponentIndex.Domain = 1;
_ComponentIndex.Port = 2;
_ComponentIndex.Path = 3;
_ComponentIndex.QueryData = 4;
_ComponentIndex.Fragment = 5;
```
Causes a runtime failure, we have 
`["components/youtube_app.html", undefined, undefined, undefined, undefined, "components/youtube_app.html", undefined, undefined]`
and then `parts[_ComponentIndex.Path][0] == '/'`
fails because `_ComponentIndex.Path` is 3 rather than 5.

**Comment by alexeagle** [comment]
From the TypeScript spec:
An enum member is classified as follows:
* If the member declaration specifies no value, the member is considered a constant enum member. If the member is the first member in the enum declaration, it is assigned the value zero. Otherwise, it is assigned the value of the immediately preceding member plus one, and an error occurs if the immediately preceding member is not a constant enum member.
* If the member declaration specifies a value that can be classified as a constant enum expression (as defined below), the member is considered a constant enum member.
* Otherwise, the member is considered a computed enum member.

**Comment by martine** [comment]
https://github.com/angular/sickle/blob/master/src/sickle.ts#L590
is the enum generation.

I think maybe we should drop all the initializer stuff from there.  The only reason we care about enums is to declare their types, I think.

@calebegg

**Comment by martine** [comment]
To clarify the bug (took me a sec), the problem is that this enum has an initializer value.  TS generates one set of values (the bits above the `ComponentIndex = {}` line in the output) and then sickle gets confused and outputs a second set of values (the lines below that point).
