### ISSUE TITLE
Support array destructuring

### ISSUE THREAD

**Issue by alexeagle** [angular/sickle#99]
eg.
```
function f([x,y]: number[]) {}
```
See #96 where I started to do this, but needs more work because `number[]` must be represented as `Array<number>` in the closure typedef.

**Comment by martine** [comment]
The tricky part of this is that we need to sprinkle in non-null annotations in the generated type, recursively.
E.g. this is the correct typing of a doubly-nested destructure:

```js
/**
 * @param {!Array<!Array<string>>} param1
 */
function Destructuring2([[c]]) {
  console.log(c);
}
```

**Comment by martine** [comment]
https://github.com/angular/sickle/commit/7e4f10962dc954f6e1dc54533af45d04a6efeaf3
